### ISSUE TITLE
META ISSUE - Define here what should be done.

### ISSUE THREAD

**Issue by tcanabrava** [JulyYuni/Blackjack#6]
- [ ] Implement a system for cards
     * Cards have two sides, each side has possible informations.
     * The most common information is the color on one side, and on the other side the number and the symbol (spades, clubs, hearths, spades), but there can be other possibilities, like a pokemon card. it's important to make a card system that can adapt. 
 - [ ] Implement a system for decks
     * a deck is a collection of cards, they can represent the entire deck or a "hand" on a player, or the discard pile.
- [ ] Implement a Player, that can be used for humans or computers, class, that have a "play", "pass", "fetch(Deck, number_of_cards)" 
- [ ] Implement a Turn Based Game class that has the basic rules for a card game.
- [ ] Using the Game class you created, implement a BlackJack game.
- [ ] Create a Server that holds the black jack game, and a Client (using a TCP Server / TCP Client) so that we can play together.
